#  ______  __  __          _    _____ _             
# |  ____|/ _|/ _|        | |  / ____| |            
# |  __| |  _|  _/ _ \/ __| __|\___ \| __/ _` | '__|
# | |____| | | ||  __/ (__| |_ ____) | || (_| | |   
# |______|_| |_| \___|\___|\__|_____/ \__\__,_|_|   
                                                  
                                                   
Effect ID: 5 
# ^^ 5 is the effect id for strength
Effect Duration: 6000
# ^^ 6 Seconds Is how Long The Effect will be given for
Effect Amp: 2
# ^^ This Means That The Player Will Recieve Strength 2
Effect Visible: true
# ^^ If this is false the player will not see any particles